getPinAssignMode -pinEditInBatch -quiet
uiSetTool ruler
set ptngSprNoRefreshPins 1
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[0]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[1]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[2]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[3]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[4]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[5]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[6]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[7]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[8]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[9]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[10]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[11]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[12]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[13]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[14]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[15]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[16]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[17]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[18]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[19]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[20]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[21]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[22]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[23]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[24]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[25]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[26]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {sum_out_core_three[27]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[0]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[1]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[2]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[3]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[4]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[5]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[6]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[7]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[8]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[9]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[10]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[11]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[12]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[13]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[14]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[15]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[16]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[17]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[18]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[19]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[20]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[21]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[22]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[23]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[24]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[25]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[26]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_to_core_three[27]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[0]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[1]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[2]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[3]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[4]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[5]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[6]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[7]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[8]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[9]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[10]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[11]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[12]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[13]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[14]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[15]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[16]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[17]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[18]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[19]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[20]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[21]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[22]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[23]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[24]} -status unplaced -silent
setPtnPinStatus -cell cross_core_adder -pin {core_sum_in_from_core_three[25]} -status unplaced -silent
set ptngSprNoRefreshPins 0
ptnSprRefreshPinsAndBlockages
setPinAssignMode -pinEditInBatch true
editPin -fixedPin 1 -fixOverlap 1 -spreadDirection clockwise -side Left -layer 1 -spreadType range -start 0.0 10.0 -end 0.0 60.0 -pin {{sum_out_core_three[0]} {sum_out_core_three[1]} {sum_out_core_three[2]} {sum_out_core_three[3]} {sum_out_core_three[4]} {sum_out_core_three[5]} {sum_out_core_three[6]} {sum_out_core_three[7]} {sum_out_core_three[8]} {sum_out_core_three[9]} {sum_out_core_three[10]} {sum_out_core_three[11]} {sum_out_core_three[12]} {sum_out_core_three[13]} {sum_out_core_three[14]} {sum_out_core_three[15]} {sum_out_core_three[16]} {sum_out_core_three[17]} {sum_out_core_three[18]} {sum_out_core_three[19]} {sum_out_core_three[20]} {sum_out_core_three[21]} {sum_out_core_three[22]} {sum_out_core_three[23]} {sum_out_core_three[24]} {sum_out_core_three[25]} {sum_out_core_three[26]} {sum_out_core_three[27]} {core_sum_to_core_three[0]} {core_sum_to_core_three[1]} {core_sum_to_core_three[2]} {core_sum_to_core_three[3]} {core_sum_to_core_three[4]} {core_sum_to_core_three[5]} {core_sum_to_core_three[6]} {core_sum_to_core_three[7]} {core_sum_to_core_three[8]} {core_sum_to_core_three[9]} {core_sum_to_core_three[10]} {core_sum_to_core_three[11]} {core_sum_to_core_three[12]} {core_sum_to_core_three[13]} {core_sum_to_core_three[14]} {core_sum_to_core_three[15]} {core_sum_to_core_three[16]} {core_sum_to_core_three[17]} {core_sum_to_core_three[18]} {core_sum_to_core_three[19]} {core_sum_to_core_three[20]} {core_sum_to_core_three[21]} {core_sum_to_core_three[22]} {core_sum_to_core_three[23]} {core_sum_to_core_three[24]} {core_sum_to_core_three[25]} {core_sum_to_core_three[26]} {core_sum_to_core_three[27]} {core_sum_in_from_core_three[0]} {core_sum_in_from_core_three[1]} {core_sum_in_from_core_three[2]} {core_sum_in_from_core_three[3]} {core_sum_in_from_core_three[4]} {core_sum_in_from_core_three[5]} {core_sum_in_from_core_three[6]} {core_sum_in_from_core_three[7]} {core_sum_in_from_core_three[8]} {core_sum_in_from_core_three[9]} {core_sum_in_from_core_three[10]} {core_sum_in_from_core_three[11]} {core_sum_in_from_core_three[12]} {core_sum_in_from_core_three[13]} {core_sum_in_from_core_three[14]} {core_sum_in_from_core_three[15]} {core_sum_in_from_core_three[16]} {core_sum_in_from_core_three[17]} {core_sum_in_from_core_three[18]} {core_sum_in_from_core_three[19]} {core_sum_in_from_core_three[20]} {core_sum_in_from_core_three[21]} {core_sum_in_from_core_three[22]} {core_sum_in_from_core_three[23]} {core_sum_in_from_core_three[24]} {core_sum_in_from_core_three[25]}}
setPinAssignMode -pinEditInBatch true
editPin -pinWidth 0.09 -pinDepth 0.47 -fixedPin 1 -fixOverlap 1 -spreadDirection clockwise -side Left -layer 3 -spreadType range -start 0.0 10.0 -end 0.0 59.8 -pin {{sum_out_core_three[0]} {sum_out_core_three[1]} {sum_out_core_three[2]} {sum_out_core_three[3]} {sum_out_core_three[4]} {sum_out_core_three[5]} {sum_out_core_three[6]} {sum_out_core_three[7]} {sum_out_core_three[8]} {sum_out_core_three[9]} {sum_out_core_three[10]} {sum_out_core_three[11]} {sum_out_core_three[12]} {sum_out_core_three[13]} {sum_out_core_three[14]} {sum_out_core_three[15]} {sum_out_core_three[16]} {sum_out_core_three[17]} {sum_out_core_three[18]} {sum_out_core_three[19]} {sum_out_core_three[20]} {sum_out_core_three[21]} {sum_out_core_three[22]} {sum_out_core_three[23]} {sum_out_core_three[24]} {sum_out_core_three[25]} {sum_out_core_three[26]} {sum_out_core_three[27]} {core_sum_to_core_three[0]} {core_sum_to_core_three[1]} {core_sum_to_core_three[2]} {core_sum_to_core_three[3]} {core_sum_to_core_three[4]} {core_sum_to_core_three[5]} {core_sum_to_core_three[6]} {core_sum_to_core_three[7]} {core_sum_to_core_three[8]} {core_sum_to_core_three[9]} {core_sum_to_core_three[10]} {core_sum_to_core_three[11]} {core_sum_to_core_three[12]} {core_sum_to_core_three[13]} {core_sum_to_core_three[14]} {core_sum_to_core_three[15]} {core_sum_to_core_three[16]} {core_sum_to_core_three[17]} {core_sum_to_core_three[18]} {core_sum_to_core_three[19]} {core_sum_to_core_three[20]} {core_sum_to_core_three[21]} {core_sum_to_core_three[22]} {core_sum_to_core_three[23]} {core_sum_to_core_three[24]} {core_sum_to_core_three[25]} {core_sum_to_core_three[26]} {core_sum_to_core_three[27]} {core_sum_in_from_core_three[0]} {core_sum_in_from_core_three[1]} {core_sum_in_from_core_three[2]} {core_sum_in_from_core_three[3]} {core_sum_in_from_core_three[4]} {core_sum_in_from_core_three[5]} {core_sum_in_from_core_three[6]} {core_sum_in_from_core_three[7]} {core_sum_in_from_core_three[8]} {core_sum_in_from_core_three[9]} {core_sum_in_from_core_three[10]} {core_sum_in_from_core_three[11]} {core_sum_in_from_core_three[12]} {core_sum_in_from_core_three[13]} {core_sum_in_from_core_three[14]} {core_sum_in_from_core_three[15]} {core_sum_in_from_core_three[16]} {core_sum_in_from_core_three[17]} {core_sum_in_from_core_three[18]} {core_sum_in_from_core_three[19]} {core_sum_in_from_core_three[20]} {core_sum_in_from_core_three[21]} {core_sum_in_from_core_three[22]} {core_sum_in_from_core_three[23]} {core_sum_in_from_core_three[24]} {core_sum_in_from_core_three[25]}}
setPinAssignMode -pinEditInBatch true
editPin -pinWidth 0.1 -pinDepth 0.6 -fixedPin 1 -fixOverlap 1 -spreadDirection clockwise -side Left -layer 3 -spreadType range -start 0.0 10.0 -end 0.0 59.4 -pin {{sum_out_core_three[0]} {sum_out_core_three[1]} {sum_out_core_three[2]} {sum_out_core_three[3]} {sum_out_core_three[4]} {sum_out_core_three[5]} {sum_out_core_three[6]} {sum_out_core_three[7]} {sum_out_core_three[8]} {sum_out_core_three[9]} {sum_out_core_three[10]} {sum_out_core_three[11]} {sum_out_core_three[12]} {sum_out_core_three[13]} {sum_out_core_three[14]} {sum_out_core_three[15]} {sum_out_core_three[16]} {sum_out_core_three[17]} {sum_out_core_three[18]} {sum_out_core_three[19]} {sum_out_core_three[20]} {sum_out_core_three[21]} {sum_out_core_three[22]} {sum_out_core_three[23]} {sum_out_core_three[24]} {sum_out_core_three[25]} {sum_out_core_three[26]} {sum_out_core_three[27]} {core_sum_to_core_three[0]} {core_sum_to_core_three[1]} {core_sum_to_core_three[2]} {core_sum_to_core_three[3]} {core_sum_to_core_three[4]} {core_sum_to_core_three[5]} {core_sum_to_core_three[6]} {core_sum_to_core_three[7]} {core_sum_to_core_three[8]} {core_sum_to_core_three[9]} {core_sum_to_core_three[10]} {core_sum_to_core_three[11]} {core_sum_to_core_three[12]} {core_sum_to_core_three[13]} {core_sum_to_core_three[14]} {core_sum_to_core_three[15]} {core_sum_to_core_three[16]} {core_sum_to_core_three[17]} {core_sum_to_core_three[18]} {core_sum_to_core_three[19]} {core_sum_to_core_three[20]} {core_sum_to_core_three[21]} {core_sum_to_core_three[22]} {core_sum_to_core_three[23]} {core_sum_to_core_three[24]} {core_sum_to_core_three[25]} {core_sum_to_core_three[26]} {core_sum_to_core_three[27]} {core_sum_in_from_core_three[0]} {core_sum_in_from_core_three[1]} {core_sum_in_from_core_three[2]} {core_sum_in_from_core_three[3]} {core_sum_in_from_core_three[4]} {core_sum_in_from_core_three[5]} {core_sum_in_from_core_three[6]} {core_sum_in_from_core_three[7]} {core_sum_in_from_core_three[8]} {core_sum_in_from_core_three[9]} {core_sum_in_from_core_three[10]} {core_sum_in_from_core_three[11]} {core_sum_in_from_core_three[12]} {core_sum_in_from_core_three[13]} {core_sum_in_from_core_three[14]} {core_sum_in_from_core_three[15]} {core_sum_in_from_core_three[16]} {core_sum_in_from_core_three[17]} {core_sum_in_from_core_three[18]} {core_sum_in_from_core_three[19]} {core_sum_in_from_core_three[20]} {core_sum_in_from_core_three[21]} {core_sum_in_from_core_three[22]} {core_sum_in_from_core_three[23]} {core_sum_in_from_core_three[24]} {core_sum_in_from_core_three[25]}}
setPinAssignMode -pinEditInBatch true
editPin -pinWidth 0.1 -pinDepth 0.6 -fixedPin 1 -fixOverlap 1 -spreadDirection clockwise -side Left -layer 3 -spreadType range -start 0.0 60.0 -end 0.0 110.0 -pin {{core_sum_in_from_core_two[0]} {core_sum_in_from_core_two[1]} {core_sum_in_from_core_two[2]} {core_sum_in_from_core_two[3]} {core_sum_in_from_core_two[4]} {core_sum_in_from_core_two[5]} {core_sum_in_from_core_two[6]} {core_sum_in_from_core_two[7]} {core_sum_in_from_core_two[8]} {core_sum_in_from_core_two[9]} {core_sum_in_from_core_two[10]} {core_sum_in_from_core_two[11]} {core_sum_in_from_core_two[12]} {core_sum_in_from_core_two[13]} {core_sum_in_from_core_two[14]} {core_sum_in_from_core_two[15]} {core_sum_in_from_core_two[16]} {core_sum_in_from_core_two[17]} {core_sum_in_from_core_two[18]} {core_sum_in_from_core_two[19]} {core_sum_in_from_core_two[20]} {core_sum_in_from_core_two[21]} {core_sum_in_from_core_two[22]} {core_sum_in_from_core_two[23]} {core_sum_in_from_core_two[24]} {core_sum_in_from_core_two[25]} {core_sum_to_core_two[0]} {core_sum_to_core_two[1]} {core_sum_to_core_two[2]} {core_sum_to_core_two[3]} {core_sum_to_core_two[4]} {core_sum_to_core_two[5]} {core_sum_to_core_two[6]} {core_sum_to_core_two[7]} {core_sum_to_core_two[8]} {core_sum_to_core_two[9]} {core_sum_to_core_two[10]} {core_sum_to_core_two[11]} {core_sum_to_core_two[12]} {core_sum_to_core_two[13]} {core_sum_to_core_two[14]} {core_sum_to_core_two[15]} {core_sum_to_core_two[16]} {core_sum_to_core_two[17]} {core_sum_to_core_two[18]} {core_sum_to_core_two[19]} {core_sum_to_core_two[20]} {core_sum_to_core_two[21]} {core_sum_to_core_two[22]} {core_sum_to_core_two[23]} {core_sum_to_core_two[24]} {core_sum_to_core_two[25]} {core_sum_to_core_two[26]} {core_sum_to_core_two[27]} {sum_out_core_two[0]} {sum_out_core_two[1]} {sum_out_core_two[2]} {sum_out_core_two[3]} {sum_out_core_two[4]} {sum_out_core_two[5]} {sum_out_core_two[6]} {sum_out_core_two[7]} {sum_out_core_two[8]} {sum_out_core_two[9]} {sum_out_core_two[10]} {sum_out_core_two[11]} {sum_out_core_two[12]} {sum_out_core_two[13]} {sum_out_core_two[14]} {sum_out_core_two[15]} {sum_out_core_two[16]} {sum_out_core_two[17]} {sum_out_core_two[18]} {sum_out_core_two[19]} {sum_out_core_two[20]} {sum_out_core_two[21]} {sum_out_core_two[22]} {sum_out_core_two[23]} {sum_out_core_two[24]} {sum_out_core_two[25]} {sum_out_core_two[26]} {sum_out_core_two[27]}}
setPinAssignMode -pinEditInBatch true
editPin -fixedPin 1 -fixOverlap 1 -spreadDirection clockwise -side Left -layer 3 -spreadType range -start 0.0 110.0 -end 0.0 170.0 -pin {clk {core_enable_mask[0]} {core_enable_mask[1]} {core_enable_mask[2]} {core_enable_mask[3]} {core_ext_sum_wr[0]} {core_ext_sum_wr[1]} {core_ext_sum_wr[2]} {core_ext_sum_wr[3]} {core_sum_pop_ready[0]} {core_sum_pop_ready[1]} {core_sum_pop_ready[2]} {core_sum_pop_ready[3]} ext_sum_wr_cmd {group_link[0]} {group_link[1]} {group_link[2]} {multi_core_inst[0]} {multi_core_inst[1]} {multi_core_inst[2]} {multi_core_inst[3]} reset {sum_valid_in[0]} {sum_valid_in[1]} {sum_valid_in[2]} {sum_valid_in[3]} {sum_valid_out[0]} {sum_valid_out[1]} {sum_valid_out[2]} {sum_valid_out[3]}}
setPinAssignMode -pinEditInBatch true
editPin -pinWidth 0.1 -pinDepth 0.6 -fixedPin 1 -fixOverlap 1 -spreadDirection clockwise -side Left -layer 3 -spreadType range -start 0.0 110.0 -end 0.0 169.8 -pin {clk {core_enable_mask[0]} {core_enable_mask[1]} {core_enable_mask[2]} {core_enable_mask[3]} {core_ext_sum_wr[0]} {core_ext_sum_wr[1]} {core_ext_sum_wr[2]} {core_ext_sum_wr[3]} {core_sum_pop_ready[0]} {core_sum_pop_ready[1]} {core_sum_pop_ready[2]} {core_sum_pop_ready[3]} ext_sum_wr_cmd {group_link[0]} {group_link[1]} {group_link[2]} {multi_core_inst[0]} {multi_core_inst[1]} {multi_core_inst[2]} {multi_core_inst[3]} reset {sum_valid_in[0]} {sum_valid_in[1]} {sum_valid_in[2]} {sum_valid_in[3]} {sum_valid_out[0]} {sum_valid_out[1]} {sum_valid_out[2]} {sum_valid_out[3]}}
setPinAssignMode -pinEditInBatch true
editPin -pinWidth 0.1 -pinDepth 0.6 -fixedPin 1 -fixOverlap 1 -spreadDirection clockwise -side Left -layer 3 -spreadType range -start 0.0 170.0 -end 0.0 220.0 -pin {{core_sum_in_from_core_one[0]} {core_sum_in_from_core_one[1]} {core_sum_in_from_core_one[2]} {core_sum_in_from_core_one[3]} {core_sum_in_from_core_one[4]} {core_sum_in_from_core_one[5]} {core_sum_in_from_core_one[6]} {core_sum_in_from_core_one[7]} {core_sum_in_from_core_one[8]} {core_sum_in_from_core_one[9]} {core_sum_in_from_core_one[10]} {core_sum_in_from_core_one[11]} {core_sum_in_from_core_one[12]} {core_sum_in_from_core_one[13]} {core_sum_in_from_core_one[14]} {core_sum_in_from_core_one[15]} {core_sum_in_from_core_one[16]} {core_sum_in_from_core_one[17]} {core_sum_in_from_core_one[18]} {core_sum_in_from_core_one[19]} {core_sum_in_from_core_one[20]} {core_sum_in_from_core_one[21]} {core_sum_in_from_core_one[22]} {core_sum_in_from_core_one[23]} {core_sum_in_from_core_one[24]} {core_sum_in_from_core_one[25]} {core_sum_to_core_one[0]} {core_sum_to_core_one[1]} {core_sum_to_core_one[2]} {core_sum_to_core_one[3]} {core_sum_to_core_one[4]} {core_sum_to_core_one[5]} {core_sum_to_core_one[6]} {core_sum_to_core_one[7]} {core_sum_to_core_one[8]} {core_sum_to_core_one[9]} {core_sum_to_core_one[10]} {core_sum_to_core_one[11]} {core_sum_to_core_one[12]} {core_sum_to_core_one[13]} {core_sum_to_core_one[14]} {core_sum_to_core_one[15]} {core_sum_to_core_one[16]} {core_sum_to_core_one[17]} {core_sum_to_core_one[18]} {core_sum_to_core_one[19]} {core_sum_to_core_one[20]} {core_sum_to_core_one[21]} {core_sum_to_core_one[22]} {core_sum_to_core_one[23]} {core_sum_to_core_one[24]} {core_sum_to_core_one[25]} {core_sum_to_core_one[26]} {core_sum_to_core_one[27]} {sum_out_core_one[0]} {sum_out_core_one[1]} {sum_out_core_one[2]} {sum_out_core_one[3]} {sum_out_core_one[4]} {sum_out_core_one[5]} {sum_out_core_one[6]} {sum_out_core_one[7]} {sum_out_core_one[8]} {sum_out_core_one[9]} {sum_out_core_one[10]} {sum_out_core_one[11]} {sum_out_core_one[12]} {sum_out_core_one[13]} {sum_out_core_one[14]} {sum_out_core_one[15]} {sum_out_core_one[16]} {sum_out_core_one[17]} {sum_out_core_one[18]} {sum_out_core_one[19]} {sum_out_core_one[20]} {sum_out_core_one[21]} {sum_out_core_one[22]} {sum_out_core_one[23]} {sum_out_core_one[24]} {sum_out_core_one[25]} {sum_out_core_one[26]} {sum_out_core_one[27]}}
zoomBox 242.724 93.649 247.516 80.644
fit
setPinAssignMode -pinEditInBatch true
editPin -pinWidth 0.1 -pinDepth 0.6 -fixedPin 1 -fixOverlap 1 -spreadDirection clockwise -side Left -layer 3 -spreadType range -start 0.0 220.0 -end 0.0 270.0 -pin {{core_sum_in_from_core_zero[0]} {core_sum_in_from_core_zero[1]} {core_sum_in_from_core_zero[2]} {core_sum_in_from_core_zero[3]} {core_sum_in_from_core_zero[4]} {core_sum_in_from_core_zero[5]} {core_sum_in_from_core_zero[6]} {core_sum_in_from_core_zero[7]} {core_sum_in_from_core_zero[8]} {core_sum_in_from_core_zero[9]} {core_sum_in_from_core_zero[10]} {core_sum_in_from_core_zero[11]} {core_sum_in_from_core_zero[12]} {core_sum_in_from_core_zero[13]} {core_sum_in_from_core_zero[14]} {core_sum_in_from_core_zero[15]} {core_sum_in_from_core_zero[16]} {core_sum_in_from_core_zero[17]} {core_sum_in_from_core_zero[18]} {core_sum_in_from_core_zero[19]} {core_sum_in_from_core_zero[20]} {core_sum_in_from_core_zero[21]} {core_sum_in_from_core_zero[22]} {core_sum_in_from_core_zero[23]} {core_sum_in_from_core_zero[24]} {core_sum_in_from_core_zero[25]} {core_sum_to_core_zero[0]} {core_sum_to_core_zero[1]} {core_sum_to_core_zero[2]} {core_sum_to_core_zero[3]} {core_sum_to_core_zero[4]} {core_sum_to_core_zero[5]} {core_sum_to_core_zero[6]} {core_sum_to_core_zero[7]} {core_sum_to_core_zero[8]} {core_sum_to_core_zero[9]} {core_sum_to_core_zero[10]} {core_sum_to_core_zero[11]} {core_sum_to_core_zero[12]} {core_sum_to_core_zero[13]} {core_sum_to_core_zero[14]} {core_sum_to_core_zero[15]} {core_sum_to_core_zero[16]} {core_sum_to_core_zero[17]} {core_sum_to_core_zero[18]} {core_sum_to_core_zero[19]} {core_sum_to_core_zero[20]} {core_sum_to_core_zero[21]} {core_sum_to_core_zero[22]} {core_sum_to_core_zero[23]} {core_sum_to_core_zero[24]} {core_sum_to_core_zero[25]} {core_sum_to_core_zero[26]} {core_sum_to_core_zero[27]} {sum_out_core_zero[0]} {sum_out_core_zero[1]} {sum_out_core_zero[2]} {sum_out_core_zero[3]} {sum_out_core_zero[4]} {sum_out_core_zero[5]} {sum_out_core_zero[6]} {sum_out_core_zero[7]} {sum_out_core_zero[8]} {sum_out_core_zero[9]} {sum_out_core_zero[10]} {sum_out_core_zero[11]} {sum_out_core_zero[12]} {sum_out_core_zero[13]} {sum_out_core_zero[14]} {sum_out_core_zero[15]} {sum_out_core_zero[16]} {sum_out_core_zero[17]} {sum_out_core_zero[18]} {sum_out_core_zero[19]} {sum_out_core_zero[20]} {sum_out_core_zero[21]} {sum_out_core_zero[22]} {sum_out_core_zero[23]} {sum_out_core_zero[24]} {sum_out_core_zero[25]} {sum_out_core_zero[26]} {sum_out_core_zero[27]}}
